export type Children = Readonly<{ children: React.ReactNode }>;

export type CoingeckoV3CoinsListResponseData = {
  id: string;
  symbol: string;
  name: string;
  image: string;
  current_price: number;
  market_cap: number;
  market_cap_rank: number;
  fully_diluted_valuation: number;
  total_volume: number;
  high_24h: number;
  low_24h: number;
  price_change_24h: number;
  price_change_percentage_24h: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  circulating_supply: number;
  total_supply: number;
  max_supply: number;
  ath: number;
  ath_change_percentage: number;
  ath_date: string;
  atl: number;
  atl_change_percentage: number;
  atl_date: string;
  roi: string | number;
  last_updated: string;
  sparkline_in_7d: Record<'price', number[]>;
  price_change_percentage_1h_in_currency: number;
  price_change_percentage_24h_in_currency: number;
  price_change_percentage_7d_in_currency: number;
};

export type CoingeckoV3CoinResponseData = {
  id: string;
  symbol: string;
  name: string;
  web_slug: string;
  asset_platform_id: unknown;
  platforms: unknown;
  detail_platforms: {
    decimal_place: unknown;
    contract_address: string;
  };
  block_time_in_minutes: number;
  hashing_algorithm: string;
  categories: string[];
  preview_listing: boolean;
  public_notice: unknown;
  additional_notices: unknown[];
  localization: Record<'en', string>;
  description: Record<'en', string>;
  links: {
    homepage: string[];
    whitepaper: string;
    blockchain_site: string[];
    official_forum_url: string[];
    chat_url: unknown[];
    announcement_url: unknown[];
    snapshot_url: unknown;
    twitter_screen_name: string;
    facebook_username: string;
    bitcointalk_thread_identifier: unknown;
    telegram_channel_identifier: string;
    subreddit_url: string;
    repos_url: {
      github: string[];
      bitbucket: string[];
    };
  };
  image: {
    thumb: string;
    small: string;
    large: string;
  };
  country_origin: string;
  genesis_date: string;
  sentiment_votes_up_percentage: number;
  sentiment_votes_down_percentage: number;
  watchlist_portfolio_users: number;
  market_cap_rank: number;
  market_data: {
    current_price: CurrencyToValue;
    total_value_locked: unknown;
    mcap_to_tvl_ratio: unknown;
    fdv_to_tvl_ratio: unknown;
    roi: unknown;
    ath: CurrencyToValue;
    ath_change_percentage: CurrencyToValue;
    ath_date: CurrencyToValue;
    atl: CurrencyToValue;
    atl_change_percentage: CurrencyToValue;
    atl_date: CurrencyToValue;
    market_cap: CurrencyToValue;
    market_cap_rank: number;
    fully_diluted_valuation: CurrencyToValue;
    market_cap_fdv_ratio: number;
    total_volume: CurrencyToValue;
    high_24h: CurrencyToValue;
    low_24h: CurrencyToValue;
    price_change_24h: number;
    price_change_percentage_24h: number;
    price_change_percentage_7d: number;
    price_change_percentage_14d: number;
    price_change_percentage_30d: number;
    price_change_percentage_60d: number;
    price_change_percentage_200d: number;
    price_change_percentage_1y: number;
    market_cap_change_24h: number;
    market_cap_change_percentage_24h: number;
    price_change_24h_in_currency: CurrencyToValue;
    price_change_percentage_1h_in_currency: CurrencyToValue;
    price_change_percentage_24h_in_currency: CurrencyToValue;
    price_change_percentage_7d_in_currency: CurrencyToValue;
    price_change_percentage_14d_in_currency: CurrencyToValue;
    price_change_percentage_30d_in_currency: CurrencyToValue;
    price_change_percentage_60d_in_currency: CurrencyToValue;
    price_change_percentage_200d_in_currency: CurrencyToValue;
    price_change_percentage_1y_in_currency: CurrencyToValue;
    market_cap_change_24h_in_currency: CurrencyToValue;
    market_cap_change_percentage_24h_in_currency: CurrencyToValue;
    sparkline_7d: Record<'price', number[]>;
    total_supply: number;
    max_supply: number;
    max_supply_infinite: boolean;
    circulating_supply: number;
    last_updated: string;
  };
  community_data: {
    facebook_likes: unknown;
    twitter_followers: number;
    reddit_average_posts_48h: number;
    reddit_average_comments_48h: number;
    reddit_subscribers: number;
    reddit_accounts_active_48h: number;
    telegram_channel_user_count: unknown;
  };
  developer_data: {
    forks: number;
    stars: number;
    subscribers: number;
    total_issues: number;
    closed_issues: number;
    pull_requests_merged: number;
    pull_request_contributors: number;
    code_additions_deletions_4_weeks: {
      additions: number;
      deletions: number;
    };
    commit_count_4_weeks: number;
    last_4_weeks_commit_activity_series: unknown[];
  };
  status_updates: unknown[];
  last_updated: string;
  tickers: {
    base: string;
    target: string;
    market: {
      name: string;
      identifier: string;
      has_trading_incentive: boolean;
    };
    last: number;
    volume: number;
    converted_last: {
      btc: number;
      eth: number;
      usd: number;
    };
    converted_volume: {
      btc: number;
      eth: number;
      usd: number;
    };
    trust_score: string;
    bid_ask_spread_percentage: number;
    timestamp: string;
    last_traded_at: string;
    last_fetch_at: string;
    is_anomaly: boolean;
    is_stale: boolean;
    trade_url?: string;
    token_info_url: string;
    coin_id: string;
    target_coin_id?: string;
  };
};

export type CurrencyToValue = {
  aed: number;
  ars: number;
  aud: number;
  bch: number;
  bdt: number;
  bhd: number;
  bmd: number;
  bnb: number;
  brl: number;
  btc: number;
  cad: number;
  chf: number;
  clp: number;
  cny: number;
  czk: number;
  dkk: number;
  dot: number;
  eos: number;
  eth: number;
  eur: number;
  gbp: number;
  gel: number;
  hkd: number;
  huf: number;
  idr: number;
  ils: number;
  inr: number;
  jpy: number;
  krw: number;
  kwd: number;
  lkr: number;
  ltc: number;
  mmk: number;
  mxn: number;
  myr: number;
  ngn: number;
  nok: number;
  nzd: number;
  php: number;
  pkr: number;
  pln: number;
  rub: number;
  sar: number;
  sek: number;
  sgd: number;
  sol: number;
  thb: number;
  try: number;
  twd: number;
  uah: number;
  usd: number;
  vef: number;
  vnd: number;
  xag: number;
  xau: number;
  xdr: number;
  xlm: number;
  xrp: number;
  yfi: number;
  zar: number;
  bits: number;
  link: number;
  sats: number;
};
